name: Deploy to Azure
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT}}
          script: |
            export PATH="/home/azureuser/.nvm/versions/node/v24.18.0/bin:/home/azureuser/.local/share/pnpm/bin:$PATH"
            cd ~/front-end
            git fetch origin main
            git reset --hard origin/main
            pnpm install --frozen-lockfile
            rm -rf dist
            pnpm build
            sudo systemctl restart nginx
            pm2 restart frontIoT
